### ISSUE TITLE
provider.drp: exec: "C:\\terraform\\terraform-provider-drp": file does not exist

### ISSUE THREAD

**Issue by rustychapin** [rackn/terraform-provider-drp#62]
Provider Version:  Current Stable
Terraform Version:  0.11.10
OS:  Windows Server 2012R2

I receive the following error when I run ./terraform plan:
provider.drp: exec: "C:\\terraform\\terraform-provider-drp": file does not exist

Execution:
PS C:\terraform> ls

    Directory: C:\terraform

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        12/14/2018  10:56 AM            .terraform
-a---        12/14/2018  10:49 AM       1157 l3dc.tf
-a---        12/14/2018  10:52 AM        306 provider.tf
-a---        12/14/2018  10:48 AM   22114304 terraform-provider-drp
-a---         12/7/2018   3:37 PM   30985216 terraform-provider-hyperv.exe
-a---         12/7/2018   3:18 PM   90075136 terraform.exe

PS C:\terraform> .\terraform.exe init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
PS C:\terraform> .\terraform.exe plan

Error: Error asking for user input: 1 error(s) occurred:

* provider.drp: exec: "C:\\terraform\\terraform-provider-drp": file does not exist

PS C:\terraform>

**Comment by rustychapin** [comment]
FYI I have used the same version on Ubuntu 18.04 using same terraform files and the provider loads correctly.

**Comment by galthaus** [comment]
Did you just upgrade to the latest tip version?

**Comment by rustychapin** [comment]
No I am running stable in both windows and linux installs

**Comment by galthaus** [comment]
That image isn't built for windows.  I think we are only building for linux.

**Comment by galthaus** [comment]
Actually, I guess we do.  I know we don't test or really support windows.

**Comment by rustychapin** [comment]
interesting... it does include a windows folder in the zip with the provider file in it

**Comment by galthaus** [comment]
You may need to name it with an exe extension?  Don't know for sure.

**Comment by rustychapin** [comment]
cool... i am running from linux and happy at this point.  However, probably better to not include in release if you don't test or support it on windows ;)

**Comment by galthaus** [comment]
Common build scripts.  We only really support drpcli on windows.  dr-provision can't because of linux/darwin specifics.  This should work, but ...

**Comment by rustychapin** [comment]
gotcha... and thanks for this tool it really is a step above the other tools i have used

**Comment by zehicle** [comment]
WORKAROUND NOTE FOR THREAD... Workaround is rename the file to include .exe
